name: LegendInventoryAPI
version: '${project.version}'
main: com.github.scropytr.legendinventoryapi.example.Main
api-version: 1.18
authors: [ Scropy ]
description: a simple inventory plugin
commands:
  gui:
