name: LegendInventoryAPI
version: '${project.version}'
main: com.github.scropytr.legendinventoryapi.InventoryAPI
api-version: 1.18
authors: [ Scropy ]
description: a simple inventory plugin
commands:
  test:
